dist: xenial

# os:
#     - linux


language: python
python:
    - 3.6
    - 3.7
    - 3.8
    - pypy

install:
    - pip install -r requirements.txt
    - yolk -l

script:
    - cd ${TRAVIS_BUILD_DIR}
    - python --version
    - export PYTHONPATH=`pwd`
    - echo $PYTHONPATH
    - pytest
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

notifications:
    email:
        on_success: change
        on_failure: always
