dist: xenial

# os:
#     - linux


language: python
python:
    - 3.6
    - 3.7
    - 3.8

install:
    - pip install -r requirements.txt
    - yolk -l

script:
    - cd ${TRAVIS_BUILD_DIR}
    - python --version

notifications:
    email:
        on_success: change
        on_failure: always
